version: "3.2"


services:
  app:
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:54.198.183.103"

  reverse-proxy:
    image: traefik:maroilles
    command: --api --docker.exposedbydefault=false
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
